### ISSUE TITLE
Is there a security risk in publishing nuget api key?

### ISSUE THREAD

**Issue by PMExtra** [dotnetrdf/vds-common#11]
I found that this repo contains the Nuget API Key (https://github.com/dotnetrdf/vds-common/blob/master/appveyor.yml)

I think it's a security risk because anybody can use this key to publish a new version of vds-common that may contains malicious code.

**Comment by kal** [comment]
It's not a NuGet key that you see there! The value in the appveyor.yml file is the original NuGet key encrypted using a secret known only to the Appveyor account, and is only decrypted when a deployment is triggered by making a commit to the main branch in this repo. See https://www.appveyor.com/docs/build-configuration/#secure-variables for the details (note that the secret is not decrypted on PR builds, so a malicious user can't trigger a deployment just by submitting a fake PR).
