### ISSUE TITLE
[Trie] Is there a thread safety risk in cleaning redundant nodes of Remove()

### ISSUE THREAD

**Issue by PMExtra** [dotnetrdf/vds-common#12]
Thread1: Call `Trie.Remove("abc")`.
Thread2: Call `Trie.Add("abcd", value)`.
Thread1: Found a leaf node that with keyBit `c`, set the value to null.
Thread1: Evaluate `(!node.IsRoot && !node.HasValue && node.Count == 0)` got true.
Thread2: Found the same node with keyBit `c`, but thread2 didn't notice that it will be removed.
Thread1: Call `parent.RemoveChild('c')`
……
Finally, the key `abcd` was lost.

Is this possible?

**Comment by PMExtra** [comment]
https://github.com/dotnetrdf/vds-common/blob/08aa4203deb0b95598f4b69522ffdeecc1d6c9ce/src/net40-client/Tries/AbstractTrie.cs#L106-L128

**Comment by kal** [comment]
@rvesse can correct me if I am wrong about this, but I don't believe that the Trie implementation in VDS.Common is intended to be thread-safe.

**Comment by rvesse** [comment]
> @rvesse can correct me if I am wrong about this, but I don't believe that the Trie implementation in VDS.Common is intended to be thread-safe.

Long time since I looked at this code but doesn't look like it was written to be thread safe.  There's one comment in the `ChangeLog.txt` in dotnetrdf/dotnetrdf referring to a bug with multi-threaded access to `Trie` but I couldn't see any other obvious reference to that
