### ISSUE TITLE
The .NET Standard assembly in version 1.7.0 is not signed

### ISSUE THREAD

**Issue by amardeepsingh** [dotnetrdf/vds-common#2]
The assembly in the netstandard1.4 folder of the nuget pacakge is not signed, while all of the other ones are.  I've submitted a [PR](https://github.com/dotnetrdf/vds-common/pull/1) that addresses it.

**Comment by kal** [comment]
Thanks @amardeepsingh. PR is merged and I'll be pushing an update as 1.8.0 to NuGet in a few minutes.
